title: "Hirut Gebretsadik" # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > 
  Data for Social Impact
  <br><br>
  Bridging the gap between data, insight, and strategy  
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/hirut-g/">
  View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
