title: Hirut Gebretsadik # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data for Social Impact
 Bridging the gap between data, insight and strategy  <br><br>
  <a href="https://www.linkedin.com/in/hirut-g/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
